id: brew:dockerfile-language-server
display-name: dockerfile-language-server
homepage: https://github.com/rcjsuen/dockerfile-language-server
repo: >
  https://registry.npmjs.org/dockerfile-language-server-nodejs/-/dockerfile-language-server-nodejs-0.15.0.tgz
docs: https://github.com/rcjsuen/dockerfile-language-server
package-manager:
  brew: dockerfile-language-server
  nix: dockerfile-language-server
  pacman: dockerfile-language-server
package-manager-url: https://formulae.brew.sh/formula/dockerfile-language-server
version: 0.15.0
license: MIT
category: development
tags:
  - cli
description: Language server for Dockerfiles powered by Node, TypeScript, and VSCode
source-archive: >
  https://registry.npmjs.org/dockerfile-language-server-nodejs/-/dockerfile-language-server-nodejs-0.15.0.tgz
dependencies:
  - node
executables:
  - exposure: global executable
    kind: cli
    name: docker-langserver
bottle:
  available: true
  platforms:
    - all
  root-url: https://ghcr.io/v2/homebrew/core
install-behavior:
  post-install-defined: false
install-lines:
  av: sudo av install brew:dockerfile-language-server
  brew: brew install dockerfile-language-server
  nix: nix profile install nixpkgs#dockerfile-language-server
  pacman: sudo pacman -S dockerfile-language-server
provenance:
  formula: dockerfile-language-server
  provider: brew
  source: https://formulae.brew.sh/api/formula.json
