id: brew:mk-configure
display-name: mk-configure
homepage: https://github.com/cheusov/mk-configure
repo: null
package-manager:
  apk: mk-configure
  brew: mk-configure
  debian: mk-configure
  dnf: mk-configure
  macports: mk-configure
  pacman: mk-configure
  ubuntu: mk-configure
  zypper: mk-configure
package-manager-url: https://formulae.brew.sh/formula/mk-configure
version: 0.40.0
license: BSD-2-Clause AND BSD-3-Clause AND MIT AND MIT-CMU
description: Lightweight replacement for GNU autotools
source-archive: >
  https://downloads.sourceforge.net/project/mk-configure/mk-configure/mk-configure-0.40.0/mk-configure-0.40.0.tar.gz
executables:
  - mkc_check_compiler
  - mkc_check_custom
  - mkc_check_decl
  - mkc_check_funclib
  - mkc_check_header
  - mkc_check_prog
  - mkc_check_sizeof
  - mkc_check_version
  - mkc_compiler_settings
  - mkc_install
  - mkc_which
  - mkcmake
provenance:
  formula: mk-configure
  provider: brew
  source: https://formulae.brew.sh/api/formula.json
