id: brew:dockerfile-language-server
display-name: dockerfile-language-server
homepage: https://github.com/rcjsuen/dockerfile-language-server
repo: null
package-manager:
  brew: dockerfile-language-server
  nix: dockerfile-language-server
  pacman: dockerfile-language-server
package-manager-url: https://formulae.brew.sh/formula/dockerfile-language-server
version: 0.15.0
license: MIT
description: Language server for Dockerfiles powered by Node, TypeScript, and VSCode
source-archive: >
  https://registry.npmjs.org/dockerfile-language-server-nodejs/-/dockerfile-language-server-nodejs-0.15.0.tgz
executables:
  - docker-langserver
provenance:
  formula: dockerfile-language-server
  provider: brew
  source: https://formulae.brew.sh/api/formula.json
